[domains] dont require project for domains add command (#16795)
Make it so that if you don't specify a project in `vercel domains add`,
it just adds the domain to your team, but doesn't attach it to a project

```
elliot@mac cli % pn vercel domains add awdjawdjiaodjoaiwd.com
> Success! Domain awdjawdjiaodjoaiwd.com added to elliot-dauber-team. [395ms]
```

Adding a project as well still works:

```
elliot@mac cli % pn vercel domains add awdjawdjiaodjoaiwd.com test
> Success! Domain awdjawdjiaodjoaiwd.com added to project test. [176ms]
WARNING! This domain is not configured properly. To configure it you should either:
  a) Set the following record on your DNS provider to continue: `A awdjawdjiaodjoaiwd.com 76.76.21.21` [recommended]
  b) Change your Domains's nameservers to the intended set
     Intended Nameservers    Current Nameservers         
     ns1.vercel-dns.com      -                      ✘    
     ns2.vercel-dns.com      -                      ✘    

  We will run a verification for you and you will receive an email upon completion.
  Read more: https://vercel.link/domain-configuration
```

Fails with an error message if adding non-apex domain without a project:

```
elliot@mac cli % pn vercel domains add aiwdj.awdjawdjiaodjoaiwd.com
Error: Only apex domains can be added without a project. To add the subdomain aiwdj.awdjawdjiaodjoaiwd.com, pass a project: vercel domains add aiwdj.awdjawdjiaodjoaiwd.com <project>
```

Also fixes a bug where when re-adding a domain to the same project we
would Error and say it's attached to another project. Now we say it's
already connected to **this** project:

```
elliot@mac cli % pn vercel domains add awdad.awdjawdjiaodjoaiwd.com test       
> Domain awdad.awdjawdjiaodjoaiwd.com is already assigned to project test. [202ms]
WARNING! This domain is not configured properly. To configure it you should either:
  a) Set the following record on your DNS provider to continue: `A awdad.awdjawdjiaodjoaiwd.com 76.76.21.21` [recommended]
  b) Change your Domains's nameservers to the intended set
     Intended Nameservers    Current Nameservers         
     ns1.vercel-dns.com      -                      ✘    
     ns2.vercel-dns.com      -                      ✘    

  We will run a verification for you and you will receive an email upon completion.
  Read more: https://vercel.link/domain-configuration
```

Verified that the old error still occurs when actually adding to a
different project:

```
elliot@mac cli % pn vercel domains add ajwda.awdjawdjiaodjoaiwd.com host-test
Error: Cannot add ajwda.awdjawdjiaodjoaiwd.com since it's already assigned to another project. (400)
```

---------

Co-authored-by: vercel[bot] <35613825+vercel[bot]@users.noreply.github.com>
Co-authored-by: Vercel <vercel[bot]@users.noreply.github.com>